Closes #83. Add instructions for launching the project.
JincorTech/backend-ico-dashboard pull request #84
Opened 2018-02-14 17:46 UTC by Aleserche

2018-02-14 17:52 UTC, hlogeon requested changes

2018-02-14 17:52 UTC, hlogeon commented on README.md
> +  > Note: The auth and verify services should be accessible from the outside. More in detail with the configuration of these services can be found in their readme.
Add links to auth & verify readme.md

2018-02-14 18:20 UTC, hlogeon approved these changes

2018-02-15 08:02 UTC, AlekNS approved these changes

2018-02-15 08:23 UTC, hlogeon approved these changes

2018-02-15 11:02 UTC, merged